Anorov/PySocks

socks.py

socks.create_connection compatibility with python 3.2+ socket.create_connection:
* default proxy usage if proxy omitted, cause we can set_default_proxy
* hold source_address argument (python 3.2+)

create_connection compatibility

---

socks.py

`socket.socket()`'s undocumented last argument differs between Python 2 and 3.
In Python 2.7.10, the last argument is `_sock`.
```
def __init__(self, family=AF_INET, type=SOCK_STREAM, proto=0, _sock=None):
```
https://hg.python.org/cpython/file/15c95b7d81dc/Lib/socket.py#l189
But in Python 3.4.3, the last argument is `fileno`.
```
def __init__(self, family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None):
```
https://hg.python.org/cpython/file/b4cbecbc0781/Lib/socket.py#l121
As socksocket uses Python 2 style, unexpected keyword argument error is raised when `socket.dup()` or `socket.accept()` is called. 
This fix uses `*args` and `**kwargs` to support both Python 2 and 3.
Note that I'm using PySocks with [paho-mqtt](https://pypi.python.org/pypi/paho-mqtt) to connect to an MQTT server …

Fix unexpected keyword argument in Python 3

---

socks.py
test/sockstest.py

`socket.create_connection` implements Happy Eyeballs/RFC6555. This means that on dual-stack machines, it's impossible to connect to a lot of hosts, even though IPv4 actually works. The workaround for this is to just synchronously raise `socket.error` instead of the `ValueError` we'd otherwise get. This way, the Happy Eyeballs algorithm knows that IPv6 doesn't work -- but as long as IPv4 works, the connection succeeds.
This is an important patch, because in many other contexts it's impossible to work around. Suppose that you want to connect to `http://www.company.example` using urllib2. Before this patch, you can't even connect to that host by manually resolving the IPv4 address and using that (e.g. `http://1.2.3.4`), because:
1. Your client will submit a Host header
2. The server will …

Support dual-stack IPv4/IPv6 environments

---

socks.py

SOCKS5 adds support for sending literal IPv6 addresses. This patch takes advantage of that support to allow applications using PySocks to request connection to literal IPv6 addresses, and to allow local DNS resolution to resolve IPv6 addresses as well as IPv4 addresses.

Support contacting remote hosts via IPv6 literals.

---

socks.py

Fixed missing port write to proxy when doing RDNS due to indent error. Added additional socket params so only addresses supported by the local interface family are returned.  This allows ipv4/ipv6 addresses to be returned only if the local system has the respective family configured, preventing lookup failures

RDNS and Resolve Local fixes

---

README.md

These two sentences together were misleading. I've added extra space to separate the, so you wouldn't use `settimeout` **after** connection is established ;)

Additional space.

---

socks.py

The following snippet fails with TCP because dns is using setblocking(False) before calling connect:
```
#!/usr/bin/env python
import socks
import dns.dnssec
import dns.exception
import dns.flags
import dns.message
import dns.name
import dns.query
import dns.rcode
import dns.rdataclass
import dns.rdatatype
import dns.resolver
socks.set_default_proxy(socks.SOCKS5, '127.0.0.1', 1080, False)
dns.query.socket.socket = socks.socksocket
if __name__ == '__main__':
rdclass = dns.rdataclass.IN
rdtype = dns.rdatatype.A
qname = dns.name.from_text('www')
req = dns.message.make_query(qname, rdtype, rdclass)
print dns.query.udp(req, '8.8.8.8', 1, 53)
print dns.query.tcp(req, '8.8.8.8', 1, 53)
```
```
Traceback (most recent call last):
File "./break.py", line 26, in <module>
print dns.query.tcp(req, …
```

workaround non-blocking issues with TCP

---

socks.py

A corner case uncovered while testing urllib3 with pysocks 1.5.7 - getaddrinfo('localhost', ...) on windows return an ipv6 address first. In case the target is bound to an ipv4 address the connection is refused and code abort before evaluating the ipv4 entry.
a regression introduced  in #35.

allow error where target is only listening to ipv4 and connection is attempted at ipv6

---

socks.py

Under Windows the module was failing because Python < 3 doesn't include
socket.inet_ntop & socket.inet_pton functions. (See issue #47 )
This modification adds the Windows functionality and notifies the user if the win_inet_pton module is missing. 
(would be better to add a requirement for win_inet_pton in the setup.py script, but I have no idea how to make different requirements for different OSes)

Adding Windows compatibility

---

socks.py

it would probably be too hard to piggyback on the caller's
handling of non blocking sockets to really handle a non-blocking
negociation - delay the timeout until we negociated.
side-effect for callers: blocking on connect in event loops, which
is very bad.
```
#!/usr/bin/env python
import socks
import socket
import errno
socks.set_default_proxy(socks.SOCKS5, '127.0.0.1', 1080, False)
socket.socket = socks.socksocket
if __name__ == '__main__':
so = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
so.setblocking(0)
try:
so.connect(('test.host',53))
except socket.error as e:
if e.args[0] == errno.EINPROGRESS:
pass
print(so.getsockname())
```
(consider this a weak proposal, I already messed up on py3)

workaround nonblocking connects

---

socks.py

It is possible when setting timeouts on socksocket objects to find that they hang indefinitely during connection or negotiation. This is a less-than-ideal user experience. This change moves the socket timeout setting earlier in the connection setup so that it applies to the actual TCP connection and the negotiation, if there is any.
For the moment I haven't written any tests because this would require some extra logic to handle. Let me know if that's something you actually want and I can invest the time to write those tests.

Timeout earlier in connection.

---

CHANGELOG.md
socks.py

This should make us more compatible with alternate socket implementations, in particular gevent's.
Fixes #61.
(I couldn't run the tests locally, so this may take an iteration or two on Travis.)

Use super() instead of hardcoding a class.

---

requirements_dev.txt
tox.ini

Use exact version of test server to avoid possible compatibility errors with future versions of test_server

Use test_server==0.0.26 for testing

---

socks.py

Report failures for all resolved addresses when opening a new connection through SOCKS when using `socket.create_connection()`.
Python's std-lib utility code in `socket.create_connection()` tries all resolved addresses in a loop, reports only the last error.
Without this logging statement, the reported failure *usually* is "IPv6 not supported",
because that is the last resolved address.

feat(log): report every connection failure in DEBUG level

---

setup.py

Just by changing a single line, now it is possible to build and deploy "wheels" in PyPi,
with this `python setup.py bdist_wheel` in cmd-line.
The commands to build and deploy "wheels" in PyPi, are these:
```bash
python setup.py bdist_wheel
twine upload -s dist/*
```

chore(build): use setuptools in setup.py to support wheel

---

socks.py

Ran across this when trying to use PySocks as a drop-in for SocksiPy. 298d7c9 renamed a bunch of methods and aliased them to their old names, however it changed one of the kwargs for setproxy() and setdefaultproxy() which breaks any invocations explicitly using the old kwargs.
This is pretty minor and I'm unsure if it's worth the trouble to fix so feel free to close if necessary

Make SocksiPy legacy functions kwarg-compatible

---

socks.py

- Like #70, but also for negotiation errors (e.g. user/pswd denied
messages).
- Increase log-level from DEBUG-->WARNING because if dest-address
resolves to multiple IPs, practically that is the only place where the
real failure-cause it is reported.
- Correct way should have been to log from within Python's
`socket.create_connection()`.
- FIX `ProxyError` exception that did not set `args` and, among others, repr() is empty.

feat(log): also report negotiations error in WARN level

---

.travis.yml

The Python 3.3 base version needs to be used to get py33 to work with tox on travis.

Fix tox testing on travis for Python 3.3

---

socks.py

This is necessary for modules that call `create_connection()` with `timeout` and `source_address` used as positional parameters, like `http.client`.

Make create_connection() signature match socket module

---

socks.py

If the SOCKS5 server requests username/pasword authentication and
if we do not have username/password, raise SOCKS5AuthError instead of
TypeError.

Prevent TypeError in case Server requests unsupported authentication.

---

socks.py

Using connect(), I implemented connect_ex() so it returns error codes. The only cased where it won't return error codes is when the error is a socks error, not a socket error

adds connect_ex method just like the original socket module

---

setup.py

Right now https://pypi.org/project/PySocks/ looks like:
The good news is the new PyPI (aka Warehouse) now supports Markdown for the description, so we can use README.md without conversion!
For more info and examples:
* https://pypi.org/project/markdown-description-example/
* https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
* https://github.com/di/markdown-description-example

Use README.md as description on PyPI
